"""Pin the taxonomy members no other test file exercises.

The adversarial test audit diffed the union of all test SQL against the
StatementKind/AlterTableActionKind enums; these examples close the gaps that
are plausible in real migrations (the remainder — two-phase commit, SHOW,
database/tablespace DDL — is pinned in test_coverage_gaps.py).
"""

from __future__ import annotations

import pytest
from helpers import only_action, only_statement

from pgverdict import AlterTableActionKind, QualifiedName, StatementKind


@pytest.mark.parametrize(
    ("sql", "kind", "target"),
    [
        (
            "ALTER VIEW active_users SET (security_barrier = true);",
            StatementKind.ALTER_VIEW,
            QualifiedName("active_users"),
        ),
        (
            "ALTER MATERIALIZED VIEW reporting.daily_totals SET (autovacuum_enabled = false);",
            StatementKind.ALTER_MATVIEW,
            QualifiedName("daily_totals", schema="reporting"),
        ),
        (
            "ALTER TYPE money_amount ADD ATTRIBUTE fee numeric;",
            StatementKind.ALTER_COMPOSITE_TYPE,
            QualifiedName("money_amount"),
        ),
        (
            "ALTER MATERIALIZED VIEW daily_totals RENAME TO daily_rollups;",
            StatementKind.RENAME_MATVIEW,
            QualifiedName("daily_totals"),
        ),
        (
            "DROP SCHEMA legacy CASCADE;",
            StatementKind.DROP_SCHEMA,
            None,
        ),
    ],
)
def test_statement_kinds(sql: str, kind: StatementKind, target: QualifiedName | None) -> None:
    statement = only_statement(sql)
    assert statement.kind is kind
    if target is not None:
        assert statement.targets == (target,)


@pytest.mark.parametrize(
    ("sql", "kind", "column"),
    [
        (
            "ALTER TABLE users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;",
            AlterTableActionKind.ADD_IDENTITY,
            "id",
        ),
        (
            "ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;",
            AlterTableActionKind.SET_IDENTITY,
            "id",
        ),
        (
            "ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS;",
            AlterTableActionKind.DROP_IDENTITY,
            "id",
        ),
        (
            "ALTER TABLE events ALTER COLUMN payload SET COMPRESSION lz4;",
            AlterTableActionKind.SET_COMPRESSION,
            "payload",
        ),
        (
            "ALTER TABLE orders ALTER COLUMN total SET EXPRESSION AS (qty * unit_price);",
            AlterTableActionKind.SET_EXPRESSION,
            "total",
        ),
        (
            "ALTER TABLE orders ALTER COLUMN total DROP EXPRESSION;",
            AlterTableActionKind.DROP_EXPRESSION,
            "total",
        ),
        (
            "ALTER TABLE orders ENABLE RULE protect_archived;",
            AlterTableActionKind.ENABLE_RULE,
            None,
        ),
        (
            "ALTER TABLE orders DISABLE RULE protect_archived;",
            AlterTableActionKind.DISABLE_RULE,
            None,
        ),
        (
            "ALTER TABLE staging_orders INHERIT orders_base;",
            AlterTableActionKind.INHERIT,
            None,
        ),
        (
            "ALTER TABLE staging_orders NO INHERIT orders_base;",
            AlterTableActionKind.NO_INHERIT,
            None,
        ),
        (
            "ALTER TABLE addresses OF address_type;",
            AlterTableActionKind.OF_TYPE,
            None,
        ),
        (
            "ALTER TABLE addresses NOT OF;",
            AlterTableActionKind.NOT_OF,
            None,
        ),
    ],
)
def test_alter_table_action_kinds(
    sql: str, kind: AlterTableActionKind, column: str | None
) -> None:
    action = only_action(sql)
    assert action.kind is kind
    if column is not None:
        assert action.column == column


def test_trigger_and_rule_names_live_in_constraint_name() -> None:
    # Documented field reuse: constraint_name doubles as the toggled
    # trigger/rule name (see AlterTableAction docstring).
    action = only_action("ALTER TABLE orders DISABLE RULE protect_archived;")
    assert action.constraint_name == "protect_archived"
